'use client';

import { useEffect, useLayoutEffect, useRef, useState, type KeyboardEvent, type MouseEvent } from 'react';
import { ArrowLeft, ArrowRight, Expand, Minus, Plus, X } from 'lucide-react';
import styles from './post-images.module.css';

export type PostImageMedia = { id: string; url: string; mime: string; description?: string | null; width?: number | null; height?: number | null };
type OpenImage = { id: string; trigger: HTMLButtonElement };
const zoomLevels = [50, 75, 100, 125, 150, 200, 250, 300];
const knownDimensions = new Map<string, { width: number; height: number }>();

function rememberDimensions(image: HTMLImageElement) {
  if (image.naturalWidth > 0 && image.naturalHeight > 0) {
    knownDimensions.set(image.getAttribute('src') || image.src, { width: image.naturalWidth, height: image.naturalHeight });
    if (knownDimensions.size > 500) knownDimensions.delete(knownDimensions.keys().next().value!);
  }
}

function imageDimensions(image: PostImageMedia) {
  return image.width && image.height && image.width > 0 && image.height > 0
    ? { width: image.width, height: image.height } : knownDimensions.get(image.url) || {};
}

export function PostImages({ media }: { media: PostImageMedia[] }) {
  const images = media.filter(image => image.mime.startsWith('image/'));
  const [opened, setOpened] = useState<OpenImage | null>(null);
  if (!images.length) return null;

  return <div className={styles.gallery} aria-label={`帖子图片，共 ${images.length} 张`}>
    {images.map((image, index) => <button type="button" key={image.id} className={styles.openImage}
      aria-label={`查看第 ${index + 1} 张图片，共 ${images.length} 张`}
      onClick={event => setOpened({ id: image.id, trigger: event.currentTarget })}>
      <span className={styles.imageHeading}><span>图片 {index + 1} / {images.length}</span><span><Expand size={14}/>查看大图</span></span>
      <img src={image.url} {...imageDimensions(image)} alt={image.description || `帖子图片 ${index + 1}`} loading="lazy" decoding="async" onLoad={event => rememberDimensions(event.currentTarget)}/>
    </button>)}
    {opened && <ImageViewer images={images} opened={opened} onClose={() => setOpened(null)}/>}
  </div>;
}

function ImageViewer({ images, opened, onClose }: { images: PostImageMedia[]; opened: OpenImage; onClose: () => void }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const closeButton = useRef<HTMLButtonElement>(null);
  const viewport = useRef<HTMLDivElement>(null);
  const figures = useRef(new Map<string, HTMLElement>());
  const thumbnails = useRef<HTMLDivElement>(null);
  const scrollFrame = useRef<number | null>(null);
  const pendingScroll = useRef<{ top: number; left: number } | null>(null);
  const navigationTarget = useRef<string | null>(opened.id);
  // A short final image cannot always reach the viewport's top. Keep explicit
  // navigation selected until the reader actually scrolls, rather than letting
  // the scroll event generated by scrollTo select the preceding image again.
  const explicitSelection = useRef(true);
  const [activeId, setActiveId] = useState(opened.id);
  const [continuous, setContinuous] = useState(true);
  const [zoom, setZoom] = useState(100);
  const [failed, setFailed] = useState<string[]>([]);
  const index = Math.max(0, images.findIndex(image => image.id === activeId));
  const current = images[index];

  useEffect(() => {
    const element = dialog.current;
    if (!element) return;
    const scroll = { x: window.scrollX, y: window.scrollY };
    const properties = ['position', 'top', 'left', 'right', 'width', 'overflow', 'padding-right'];
    const saved = properties.map(name => ({ name, value: document.body.style.getPropertyValue(name), priority: document.body.style.getPropertyPriority(name) }));
    const scrollbar = window.innerWidth - document.documentElement.clientWidth;
    const padding = parseFloat(getComputedStyle(document.body).paddingRight) || 0;
    document.body.style.position = 'fixed';
    document.body.style.top = `${-scroll.y}px`;
    document.body.style.left = `${-scroll.x}px`;
    document.body.style.right = '0';
    document.body.style.width = '100%';
    document.body.style.overflow = 'hidden';
    if (scrollbar > 0) document.body.style.paddingRight = `${padding + scrollbar}px`;
    element.showModal();
    closeButton.current?.focus({ preventScroll: true });
    const frame = requestAnimationFrame(settleNavigation);
    return () => {
      cancelAnimationFrame(frame);
      if (scrollFrame.current !== null) cancelAnimationFrame(scrollFrame.current);
      element.close();
      for (const { name, value, priority } of saved) {
        if (value) document.body.style.setProperty(name, value, priority);
        else document.body.style.removeProperty(name);
      }
      window.scrollTo({ left: scroll.x, top: scroll.y, behavior: 'instant' });
      if (opened.trigger.isConnected) opened.trigger.focus({ preventScroll: true });
    };
  }, [opened]);

  useLayoutEffect(() => {
    if (pendingScroll.current && viewport.current) {
      viewport.current.scrollTo({ ...pendingScroll.current, behavior: 'instant' });
      pendingScroll.current = null;
    }
  }, [zoom]);

  useLayoutEffect(() => { explicitSelection.current = true; navigationTarget.current = current.id; settleNavigation(); }, [continuous]);
  useLayoutEffect(() => { if (navigationTarget.current) settleNavigation(); }, [current.id]);
  useLayoutEffect(() => { if (navigationTarget.current) settleNavigation(); }, [failed]);

  useEffect(() => {
    const strip = thumbnails.current;
    const selected = strip?.querySelector<HTMLElement>('[aria-current="true"]');
    if (strip && selected) {
      if (selected.offsetLeft < strip.scrollLeft) strip.scrollLeft = selected.offsetLeft;
      else if (selected.offsetLeft + selected.offsetWidth > strip.scrollLeft + strip.clientWidth) strip.scrollLeft = selected.offsetLeft + selected.offsetWidth - strip.clientWidth;
    }
  }, [current.id]);

  function scrollToImage(id: string) {
    const view = viewport.current, figure = figures.current.get(id);
    if (!view || !figure) return;
    view.scrollTo({ top: view.scrollTop + figure.getBoundingClientRect().top - view.getBoundingClientRect().top - 16, left: 0, behavior: 'instant' });
  }

  function settleNavigation() {
    const id = navigationTarget.current;
    if (!id) return;
    scrollToImage(id);
    const destination = images.findIndex(image => image.id === id);
    const preceding = continuous ? images.slice(0, destination + 1) : [images[destination]];
    if (preceding.every(image => image && figures.current.get(image.id)?.querySelector('img')?.complete)) navigationTarget.current = null;
  }

  function goTo(nextIndex: number) {
    const next = images[nextIndex];
    if (!next) return;
    explicitSelection.current = true;
    navigationTarget.current = next.id;
    setActiveId(next.id);
    settleNavigation();
  }

  function updateZoom(value: number) {
    if (value === zoom) return;
    explicitSelection.current = true;
    navigationTarget.current = null;
    const view = viewport.current;
    if (view) {
      const ratio = value / zoom;
      pendingScroll.current = { top: view.scrollTop * ratio, left: Math.max(0, (view.scrollLeft + view.clientWidth / 2) * ratio - view.clientWidth / 2) };
    }
    setZoom(value);
  }

  function zoomBy(direction: number) {
    const next = zoomLevels[zoomLevels.indexOf(zoom) + direction];
    if (next) updateZoom(next);
  }

  function keyboard(event: KeyboardEvent<HTMLDialogElement>) {
    if (event.altKey || event.ctrlKey || event.metaKey) return;
    if (event.key === 'ArrowLeft' || event.key === 'ArrowRight') {
      event.preventDefault(); goTo(index + (event.key === 'ArrowLeft' ? -1 : 1));
    } else if (event.key === '+' || event.key === '=') { event.preventDefault(); zoomBy(1); }
    else if (event.key === '-') { event.preventDefault(); zoomBy(-1); }
    else if (event.key === '0') { event.preventDefault(); updateZoom(100); }
  }

  function trackReading() {
    if (!continuous || explicitSelection.current || navigationTarget.current || scrollFrame.current !== null) return;
    scrollFrame.current = requestAnimationFrame(() => {
      scrollFrame.current = null;
      const view = viewport.current;
      if (!view || explicitSelection.current || navigationTarget.current) return;
      const edge = view.getBoundingClientRect().top + 48;
      let visible = images[0];
      for (const image of images) {
        const figure = figures.current.get(image.id);
        if (figure && figure.getBoundingClientRect().top <= edge) visible = image;
        else break;
      }
      const last = images.at(-1), lastFigure = last && figures.current.get(last.id);
      if (last && lastFigure && view.scrollTop + view.clientHeight >= view.scrollHeight - 2 && lastFigure.getBoundingClientRect().top < view.getBoundingClientRect().bottom) visible = last;
      if (visible) setActiveId(visible.id);
    });
  }

  function resumeReading() {
    explicitSelection.current = false;
    navigationTarget.current = null;
  }

  function backdrop(event: MouseEvent<HTMLDialogElement>) { if (event.target === event.currentTarget) onClose(); }

  return <dialog ref={dialog} className={styles.dialog} aria-label="帖子图片浏览器" onCancel={event => { event.preventDefault(); onClose(); }} onClick={backdrop} onKeyDown={keyboard}>
    <header className={styles.header}>
      <div className={styles.title}><strong>图片浏览</strong><span role="status">{index + 1} / {images.length}</span></div>
      <button ref={closeButton} type="button" className={styles.close} aria-label="关闭图片浏览器" onClick={onClose}><X size={22}/></button>
    </header>
    <div className={styles.toolbar} aria-label="图片阅读操作">
      <div className={styles.navigation}>
        <button type="button" disabled={index === 0} aria-label="上一张图片" onClick={() => goTo(index - 1)}><ArrowLeft size={17}/><span>上一张</span></button>
        <button type="button" disabled={index === images.length - 1} aria-label="下一张图片" onClick={() => goTo(index + 1)}><span>下一张</span><ArrowRight size={17}/></button>
      </div>
      <div className={styles.zoom}>
        <button type="button" aria-label="缩小图片" disabled={zoom === zoomLevels[0]} onClick={() => zoomBy(-1)}><Minus size={17}/></button>
        <span aria-live="polite">{zoom}%</span>
        <button type="button" aria-label="放大图片" disabled={zoom === zoomLevels.at(-1)} onClick={() => zoomBy(1)}><Plus size={17}/></button>
        <button type="button" onClick={() => updateZoom(100)}>适合宽度</button>
      </div>
      <button type="button" aria-pressed={continuous} className={styles.mode} onClick={() => setContinuous(value => !value)}>{continuous ? '连续阅读' : '单张阅读'}</button>
    </div>
    <div ref={viewport} className={styles.viewport} tabIndex={0} aria-label={continuous ? '连续阅读图片，可上下滚动' : '当前图片，可上下滚动'} onScroll={trackReading}
      onWheel={resumeReading} onPointerDown={resumeReading}
      onKeyDown={event => { if (['ArrowUp', 'ArrowDown', 'PageUp', 'PageDown', 'Home', 'End', ' '].includes(event.key)) resumeReading(); }}>
      <div className={styles.reading} style={{ width: `${zoom}%` }}>
        {(continuous ? images : [current]).map(image => {
          const position = images.findIndex(item => item.id === image.id) + 1;
          return <figure key={image.id} ref={element => { if (element) figures.current.set(image.id, element); else figures.current.delete(image.id); }} className={styles.figure}>
            <figcaption>图片 {position} / {images.length}</figcaption>
            <img src={image.url} {...imageDimensions(image)} alt={image.description || `帖子图片 ${position}`} draggable={false}
              onLoad={event => { rememberDimensions(event.currentTarget); settleNavigation(); }}
              onError={() => setFailed(previous => previous.includes(image.id) ? previous : [...previous, image.id])}/>
            {failed.includes(image.id) && <p className={styles.error} role="alert">这张图片暂时无法加载，请稍后重新打开。</p>}
          </figure>;
        })}
      </div>
    </div>
    {images.length > 1 && <div ref={thumbnails} className={styles.thumbnails} aria-label="选择图片">
      {images.map((image, imageIndex) => <button key={image.id} type="button" aria-label={`转到第 ${imageIndex + 1} 张图片`} aria-current={image.id === current.id ? 'true' : undefined} onClick={() => goTo(imageIndex)}>
        <img src={image.url} alt="" loading="lazy"/><span>{imageIndex + 1}</span>
      </button>)}
    </div>}
  </dialog>;
}
